### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by bashu** [j4mie/django-spurl#11]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by j4mie** [comment]
I agree. I've just given you commit rights.

If/when you need to push a new release, email me - jamie.matthews@gmail.com - with your PyPI account details and I'll give you the necessary permissions. Ditto any other information you need.

Thanks!
