### ISSUE TITLE
Default branch and travis ci service

### ISSUE THREAD

**Issue by bashu** [j4mie/django-spurl#14]
Hey,

Can you set "develop" branch as default, like this

![screen shot 2015-05-23 at 12 03 47](https://cloud.githubusercontent.com/assets/144783/8506849/e3da046a-2242-11e5-901f-1baf2778fbb6.png)

and enable "travis ci" service? I don't have permission to do this myself

Thanks!

**Comment by j4mie** [comment]
Done!
