### ISSUE TITLE
Doesn't work with Django 2.0

### ISSUE THREAD

**Issue by adambrenecki** [j4mie/django-spurl#22]
It appears that `spurl/templatetags/spurl.py` tries to import `django.template.StringOrigin`, which was [removed in 1.9, with the alias to `Origin` being removed in 2.0](https://docs.djangoproject.com/en/2.0/releases/1.9/#template-loaderorigin-and-stringorigin-are-removed).

Changing the import to `Origin` appears to at least allow spurl to load; I haven't tested further than that yet.

**Comment by bashu** [comment]
fixed in 0.6.5
