### ISSUE TITLE
Was removing requirements.txt intentional?

### ISSUE THREAD

**Issue by 2trc** [j4mie/django-spurl#28]
Hello guys and thank you so much for  this project! I'm very grateful as it's very handy and a must have tool (for me at least).

I was about to offer a pull request but going through the README.md and trying to run the nose tests to start with, I noticed the "requirements.txt" file is missing from the repo:

_How to run the tests  
Spurl is tested with nose. Clone the repository, then run pip install -r requirements.txt to install nose and Django into your virtualenv. Then, simply type nosetests to find and run all the tests._

After some digging, I noticed it was removed from this commit 9e7bdf3

I can probably figure out the dependencies but just wanted to double-check if this was intentional

Thanks again

**Comment by bashu** [comment]
to @2trc checkout `develop` and try again
